# Site settings
title: Software Ninjas
email: info@softwareninjas.ca
description: "Software development excellence, tools and support. The experts at integrating Team Foundation Server (TFS) with Jenkins."
baseurl: ""
url: "http://softwareninjas.ca"
twitter_username: softwareninjas
github_username: softwareninjas

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
